INSERT INTO artistas(nombre, genero, pais) VALUES ('Coldplay', 'Pop Rock', 'Reino Unido');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Bad Bunny', 'Reggaeton', 'Puerto Rico');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Metallica', 'Heavy Metal', 'Estados Unidos');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Taylor Swift', 'Pop', 'Estados Unidos');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Shakira', 'Pop Latino', 'Colombia');
INSERT INTO artistas(nombre, genero, pais) VALUES ('The Weeknd', 'R&B', 'Canada');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Ozuna', 'Reggaeton', 'Puerto Rico');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Imagine Dragons', 'Rock Alternativo', 'Estados Unidos');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Rosalia', 'Pop Flamenco', 'España');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Ed Sheeran', 'Pop', 'Reino Unido');
INSERT INTO artistas(nombre, genero, pais) VALUES ('AC/DC', 'Hard Rock', 'Australia');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Daddy Yankee', 'Reggaeton', 'Puerto Rico');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Billie Eilish', 'Pop Alternativo', 'Estados Unidos');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Los Bunkers', 'Rock', 'Chile');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Mon Laferte', 'Pop Rock', 'Chile');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Dua Lipa', 'Pop', 'Reino Unido');
INSERT INTO artistas(nombre, genero, pais) VALUES ('J Balvin', 'Reggaeton', 'Colombia');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Queen', 'Rock Clasico', 'Reino Unido');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Adele', 'Soul', 'Reino Unido');
INSERT INTO artistas(nombre, genero, pais) VALUES ('Guns N Roses', 'Hard Rock', 'Estados Unidos');